### ISSUE TITLE
Write test for simplest examples

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/client_met_council_wrangler_utilities#8]
Tests:
- [x] read log file to log file object
- [x] create highway network change project card skeleton

**Comment by e-lo** [comment]
Per our discussion today about tests, you might want to use a @pytest.fixture function to take care of some of the 'work' that needs to happen across multiple tests.  

This site has an okay example of how to implement (go to halfway down):
 - https://semaphoreci.com/community/tutorials/testing-python-applications-with-pytest

**Comment by i-am-sijia** [comment]
Do we have any example project card skeleton if nodes are added/changed?   Does it fit the existing project card schema?

**Comment by e-lo** [comment]
@i-am-sijia , this is the transit change example we worked on at last-week's stand-up:

```
Project: Bus Reroute
Category: Transit Route Change
Tags: existing_plus_committed
Dependencies:
   Prerequisites: None
   Corequisites: None
   Conflicts: None
Facility:
“short_name”: “21”
Routing:
  Replace:
    Existing: [123,-234,345]
    Set: [123,-232,233, 345]

Notes: A placeholder for notes
```

Thinking about a highway version that is similar to the PRD, this is what I came up with. But I'd also like eyes from @kulshresthaa  and @josiekre

```
Project: New Road to Nowhere
Category: New Roadway
Tags: existing_plus_committed
Dependencies:
   Prerequisites: None
   Corequisites: None
   Conflicts: None
Nodes:
    - "id": ...
      "lat": ...
      "lon": ...
        ...
Links:
   - Geometry:  # optional, if have shape geometry
      Properties:
      - "u":  123
      - "v":  124
      - "name": ..
      - "lanes": ..
      - ...etc.
   - Geometry:  # optional, if have shape geometry
      Properties:
      - "u":  124
      - "v":  125
      - "name": ..
      - "lanes": ..
      - ...etc.
Notes: A placeholder for notes
```

**Comment by i-am-sijia** [comment]
Just fyi, this is what new links (without new nodes) look like in my current structure, which is the same as the roadway change structure.

```
  category: New Roadway
  facility:
    A:
      N:
      - 3230
      - 3262
    B:
      N:
      - 3262
      - 3230
    link:
      LINK_ID:
      - 999998
      - 999997
  properties:
  - property: COUNTY
    set: 5
  - property: T_PRIORITY
    set: 0
  - property: AREA
    set: 4
 ...
  - property: T_MANTIME
    set: 0.0
```

**Comment by e-lo** [comment]
@i-am-sijia the one problem I see with this is that it relies on ordering to be correct within a list in order to match A and B nodes and Link IDs.  This is generally ok in "lists" but not safe for "dictionary" or object structures.  I would think this would be a safer to group all the attributes for single links....and then if we wanted to create a structure to have an efficient designation of properties shared among all the links, we could create one such as:

```
Nodes:
    - "id": ...
      "lat": ...
      "lon": ...
        ...
Links:
   - Geometry:  # optional, if have shape geometry
      Properties:
      - "u":  123
      - "v":  124
   - Geometry:  # optional, if have shape geometry
      Properties:
      - "u":  124
      - "v":  125
Shared_properties: #properties shared among all the links here
  - "lanes": 3
  - "...": ..., etc
```

thoughts?
